### ISSUE TITLE
Ability to save manual nonce

### ISSUE THREAD

**Issue by rrevanth** [codsane/autotss#7]
Currently, I don't think we could set config so that it will save manual nonce shsh.

It would be great it we could do that as well.

**Comment by rrevanth** [comment]
I'm not sure if it's still active but I added support for this and sent pull request to another project at
https://github.com/SpiderCab/AutoTSS/pull/4

**Comment by SpiderCab** [comment]
My project was originally copied from this project. I copied it intending to add more features, optimization, and better for users to install. Codsane doesn't agree that I should of done this and released it to the forums but my development will continue on my end and I'm actually accepting help from anyone. I honestly want this project to take off and get more attention, That is my intentions and what I'm seeking.

As for this project, I'm not sure what codsane plans to do. His intentions almost seem as if this was just for him and his friend to save their blobs hoping for a apple server incident. My intentions are for public release.

**Comment by leftyfl1p** [comment]
@rrevanth The repo you linked does not have permission to use our code. I'm not sure why you created an issue here then sent a PR over there. If you decide to change your mind and contribute here then go for it.

@SpiderCab You didn't even try to contribute here. Not a single issue or PR. Your entire project still is copied, you haven't changed a thing. Even after @codsane messaged you about not giving credit, you've ignored it and continued accepting PR's.
> as I'm not gonna wait for code to be rejected

Really? It's insulting that you openly state we're not worth the time and that you're better off stealing and re-uploading the entire project with our names stripped off it.

> I'm actually accepting help from anyone.

Yea, so are we, except both of you decided it wasn't worth even trying to contribute for who knows what reason.

> As for this project, I'm not sure what codsane plans to do. His intentions almost seem as if this was just for him and his friend to save their blobs hoping for a apple server incident. My intentions are for public release.

I don't know how you reach this conclusion when you've said nothing to us beforehand. In hindsight there should have been a proper license for contributions but we really didn't think others would be interested. Mostly because nobody has expressed this to us. You realize if this was "just for us" we could have kept it closed, right?

> but my development will continue on my end 

There is no development, you re-uploaded our project via file upload and took our names out of it. Please remove the code you have stolen from us or I will send a takedown notice.

**Comment by rrevanth** [comment]
@leftyfl1p  I didn't decided on not contributing to this project. I am not sure whether it's active since the other project has recent updated time. I thought it's  been forked to keep the project alive.

I just wanted to help. Anyway, I raised a pull request on this project as well.

**Comment by ghost** [comment]
@leftyfl1p 

Codsane has been given credit for creating AutoTSS. His name is now clearly stated on my README that he is the creator and that I have only added scripts to make the quicker and faster. I never said nor did I have intention in saying that I was the creator of AutoTSS. That is where your making your mistake. The files on my Github were suppose to be private and for me to deploy on my servers when I needed them to be. The user "AppleBlobs" on Reddit posted my project on the reddit jailbreak forums. I began to receive reports of issue people were having getting the script running so I offered help and made changes accordingly. This resulted in me creating a thread of my own to gather reports and information to optimize my area of the code which are the instructions on how to install and the scripts to actually get autotss.py running. That is where you came in and asked for the thread to be taken down when this is simply a project with the same intentions as sohsatoh's AutoTSSSaver. If you do recall, I tried to work with you asking you if you wanted credit before the moderator was contacted. You say "Even after @codsane messaged you about not giving credit". A message was never received from @codsane on Reddit nor Github. The only thing from him is his post torwards AppleBlobs attempt at defending me. 

You can proceed to process a takedown with Github if that is your wishes. My intentions are clearly stated. If your wanting to progress this and turn this into a fight, be my guest. I will simply dedicate a server and domain to hosting the codes.

I'm also gonna add that I think it's quite disrespectful for you to go off on @rrevanth , I think it's his right to choose where the code is pushed and doubt he knew that we were arguing. His help is greatly appreciated and he will get credit for adding his part.
